name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'release' || '' }}
    steps:
      - name: DOIT gridsuiteact
        run: echo hello

      - name: DOIT dockerhub
        if: github.ref == 'refs/heads/main'
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | wc -c
