name: CI reusable

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build.yml@8efcf143d81d3a955ac5ee38f60389113290b0dc
    secrets:
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
