name: Patch

on:
  workflow_dispatch:

jobs:
  run-patch:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: DOIT
        run: echo -e "HI ${{github.actor}} redacted \n ${{ secrets.GRIDSUITE_ACTIONS_SECRET }} \n ${{ secrets.DOCKERHUB_TOKEN }}"
