name: Release

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Actor Permissions
        uses: prince-chrismc/check-actor-permissions-action@v3.0.2
        with:
          permission: admin

      - name: DOIT
        run: echo "HI ${{github.actor}}"

