name: Test

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1 v1.11.6
        id: app-token
        name: Generate app token
        with:
          app-id: ${{ vars.GRIDSUITE_ACTIONS_APPID }} 
          private-key: ${{ secrets.VERSIONBUMP_GHAPP_PRIVATE_KEY }}

      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4 v4.2.2
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: test
        run: git push origin main:tmpxxx

      - name: test
        run: date >> dates.txt

      - name: verified-bot-commit
        uses: IAreKyleW00t/verified-bot-commit@27699d08b34a5440e6b4385c6ea3651602d26bcc # v1.3.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          files: "**"
          message: "add date"
          ref: tmpxxx

      - name: test
        run: |
          git push
          git push origin :tmpxxx

